## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/imdb-service
        username:  root
        password:   root123
        driverClassName: org.postgresql.Driver
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    jackson:
        default-property-inclusion: NON_NULL
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
                ddl-auto: update
                jdbc:
                    lob:
                        non_contextual_creation: true
        generate-ddl: true

